// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/loginService.proto

package it.progetto.login.grpc;

public interface CheckResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:it.progetto.progetto_sdcc.proto.CheckResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isLogged = 1;</code>
   * @return The isLogged.
   */
  boolean getIsLogged();
}
