// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/loginService.proto

package it.progetto.login.grpc;

public interface CheckUsernameResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:it.progetto.progetto_sdcc.proto.CheckUsernameResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isRegistered = 1;</code>
   * @return The isRegistered.
   */
  boolean getIsRegistered();
}
