// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/loginService.proto

package it.progetto.login.grpc;

public interface CheckRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:it.progetto.progetto_sdcc.proto.CheckRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
