// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/loginService.proto

package it.progetto.login.grpc;

public final class LoginServiceOuterClass {
  private LoginServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_it_progetto_progetto_sdcc_proto_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_it_progetto_progetto_sdcc_proto_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_it_progetto_progetto_sdcc_proto_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_it_progetto_progetto_sdcc_proto_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_it_progetto_progetto_sdcc_proto_CheckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_it_progetto_progetto_sdcc_proto_CheckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_it_progetto_progetto_sdcc_proto_CheckResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_it_progetto_progetto_sdcc_proto_CheckResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_it_progetto_progetto_sdcc_proto_ProfileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_it_progetto_progetto_sdcc_proto_ProfileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_it_progetto_progetto_sdcc_proto_ProfileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_it_progetto_progetto_sdcc_proto_ProfileResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_it_progetto_progetto_sdcc_proto_CheckUsernameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_it_progetto_progetto_sdcc_proto_CheckUsernameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_it_progetto_progetto_sdcc_proto_CheckUsernameResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_it_progetto_progetto_sdcc_proto_CheckUsernameResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%src/main/resources/loginService.proto\022" +
      "\037it.progetto.progetto_sdcc.proto\"2\n\014Logi" +
      "nRequest\022\020\n\010username\030\001 \001(\t\022\020\n\010password\030\002" +
      " \001(\t\"\035\n\rLoginResponse\022\014\n\004user\030\001 \001(\t\"\036\n\014C" +
      "heckRequest\022\016\n\006userId\030\001 \001(\t\"!\n\rCheckResp" +
      "onse\022\020\n\010isLogged\030\001 \001(\010\"1\n\016ProfileRequest" +
      "\022\016\n\006userId\030\001 \001(\t\022\017\n\007profile\030\002 \001(\t\"\"\n\017Pro" +
      "fileResponse\022\017\n\007profile\030\001 \001(\t\"(\n\024CheckUs" +
      "ernameRequest\022\020\n\010username\030\001 \001(\t\"-\n\025Check" +
      "UsernameResponse\022\024\n\014isRegistered\030\001 \001(\0102\232" +
      "\006\n\014LoginService\022f\n\005login\022-.it.progetto.p" +
      "rogetto_sdcc.proto.LoginRequest\032..it.pro" +
      "getto.progetto_sdcc.proto.LoginResponse\022" +
      "g\n\006signin\022-.it.progetto.progetto_sdcc.pr" +
      "oto.LoginRequest\032..it.progetto.progetto_" +
      "sdcc.proto.LoginResponse\022k\n\ncheckLogin\022-" +
      ".it.progetto.progetto_sdcc.proto.CheckRe" +
      "quest\032..it.progetto.progetto_sdcc.proto." +
      "CheckResponse\022g\n\006logOut\022-.it.progetto.pr" +
      "ogetto_sdcc.proto.CheckRequest\032..it.prog" +
      "etto.progetto_sdcc.proto.CheckResponse\022o" +
      "\n\ngetProfile\022/.it.progetto.progetto_sdcc" +
      ".proto.ProfileRequest\0320.it.progetto.prog" +
      "etto_sdcc.proto.ProfileResponse\022r\n\rupdat" +
      "eProfile\022/.it.progetto.progetto_sdcc.pro" +
      "to.ProfileRequest\0320.it.progetto.progetto" +
      "_sdcc.proto.ProfileResponse\022~\n\rcheckUser" +
      "name\0225.it.progetto.progetto_sdcc.proto.C" +
      "heckUsernameRequest\0326.it.progetto.proget" +
      "to_sdcc.proto.CheckUsernameResponseB\032\n\026i" +
      "t.progetto.login.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_it_progetto_progetto_sdcc_proto_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_it_progetto_progetto_sdcc_proto_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_it_progetto_progetto_sdcc_proto_LoginRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_it_progetto_progetto_sdcc_proto_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_it_progetto_progetto_sdcc_proto_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_it_progetto_progetto_sdcc_proto_LoginResponse_descriptor,
        new java.lang.String[] { "User", });
    internal_static_it_progetto_progetto_sdcc_proto_CheckRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_it_progetto_progetto_sdcc_proto_CheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_it_progetto_progetto_sdcc_proto_CheckRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_it_progetto_progetto_sdcc_proto_CheckResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_it_progetto_progetto_sdcc_proto_CheckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_it_progetto_progetto_sdcc_proto_CheckResponse_descriptor,
        new java.lang.String[] { "IsLogged", });
    internal_static_it_progetto_progetto_sdcc_proto_ProfileRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_it_progetto_progetto_sdcc_proto_ProfileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_it_progetto_progetto_sdcc_proto_ProfileRequest_descriptor,
        new java.lang.String[] { "UserId", "Profile", });
    internal_static_it_progetto_progetto_sdcc_proto_ProfileResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_it_progetto_progetto_sdcc_proto_ProfileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_it_progetto_progetto_sdcc_proto_ProfileResponse_descriptor,
        new java.lang.String[] { "Profile", });
    internal_static_it_progetto_progetto_sdcc_proto_CheckUsernameRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_it_progetto_progetto_sdcc_proto_CheckUsernameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_it_progetto_progetto_sdcc_proto_CheckUsernameRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_it_progetto_progetto_sdcc_proto_CheckUsernameResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_it_progetto_progetto_sdcc_proto_CheckUsernameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_it_progetto_progetto_sdcc_proto_CheckUsernameResponse_descriptor,
        new java.lang.String[] { "IsRegistered", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
