// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/loginService.proto

package it.progetto.login.grpc;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:it.progetto.progetto_sdcc.proto.LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user = 1;</code>
   * @return The user.
   */
  java.lang.String getUser();
  /**
   * <code>string user = 1;</code>
   * @return The bytes for user.
   */
  com.google.protobuf.ByteString
      getUserBytes();
}
