// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/loginService.proto

package it.progetto.login.grpc;

public final class LoginServiceOuterClass {
  private LoginServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_it_progetto_progetto_sdcc_proto_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_it_progetto_progetto_sdcc_proto_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_it_progetto_progetto_sdcc_proto_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_it_progetto_progetto_sdcc_proto_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_it_progetto_progetto_sdcc_proto_CheckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_it_progetto_progetto_sdcc_proto_CheckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_it_progetto_progetto_sdcc_proto_CheckResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_it_progetto_progetto_sdcc_proto_CheckResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_it_progetto_progetto_sdcc_proto_ProfileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_it_progetto_progetto_sdcc_proto_ProfileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_it_progetto_progetto_sdcc_proto_ProfileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_it_progetto_progetto_sdcc_proto_ProfileResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%src/main/resources/loginService.proto\022" +
      "\037it.progetto.progetto_sdcc.proto\"2\n\014Logi" +
      "nRequest\022\020\n\010username\030\001 \001(\t\022\020\n\010password\030\002" +
      " \001(\t\"\035\n\rLoginResponse\022\014\n\004user\030\001 \001(\t\"\036\n\014C" +
      "heckRequest\022\016\n\006userId\030\001 \001(\t\"!\n\rCheckResp" +
      "onse\022\020\n\010isLogged\030\001 \001(\010\"1\n\016ProfileRequest" +
      "\022\016\n\006userId\030\001 \001(\t\022\017\n\007profile\030\002 \001(\t\"\"\n\017Pro" +
      "fileResponse\022\017\n\007profile\030\001 \001(\t2\232\005\n\014LoginS" +
      "ervice\022f\n\005login\022-.it.progetto.progetto_s" +
      "dcc.proto.LoginRequest\032..it.progetto.pro" +
      "getto_sdcc.proto.LoginResponse\022g\n\006signin" +
      "\022-.it.progetto.progetto_sdcc.proto.Login" +
      "Request\032..it.progetto.progetto_sdcc.prot" +
      "o.LoginResponse\022k\n\ncheckLogin\022-.it.proge" +
      "tto.progetto_sdcc.proto.CheckRequest\032..i" +
      "t.progetto.progetto_sdcc.proto.CheckResp" +
      "onse\022g\n\006logOut\022-.it.progetto.progetto_sd" +
      "cc.proto.CheckRequest\032..it.progetto.prog" +
      "etto_sdcc.proto.CheckResponse\022o\n\ngetProf" +
      "ile\022/.it.progetto.progetto_sdcc.proto.Pr" +
      "ofileRequest\0320.it.progetto.progetto_sdcc" +
      ".proto.ProfileResponse\022r\n\rupdateProfile\022" +
      "/.it.progetto.progetto_sdcc.proto.Profil" +
      "eRequest\0320.it.progetto.progetto_sdcc.pro" +
      "to.ProfileResponseB\032\n\026it.progetto.login." +
      "grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_it_progetto_progetto_sdcc_proto_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_it_progetto_progetto_sdcc_proto_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_it_progetto_progetto_sdcc_proto_LoginRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_it_progetto_progetto_sdcc_proto_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_it_progetto_progetto_sdcc_proto_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_it_progetto_progetto_sdcc_proto_LoginResponse_descriptor,
        new java.lang.String[] { "User", });
    internal_static_it_progetto_progetto_sdcc_proto_CheckRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_it_progetto_progetto_sdcc_proto_CheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_it_progetto_progetto_sdcc_proto_CheckRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_it_progetto_progetto_sdcc_proto_CheckResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_it_progetto_progetto_sdcc_proto_CheckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_it_progetto_progetto_sdcc_proto_CheckResponse_descriptor,
        new java.lang.String[] { "IsLogged", });
    internal_static_it_progetto_progetto_sdcc_proto_ProfileRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_it_progetto_progetto_sdcc_proto_ProfileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_it_progetto_progetto_sdcc_proto_ProfileRequest_descriptor,
        new java.lang.String[] { "UserId", "Profile", });
    internal_static_it_progetto_progetto_sdcc_proto_ProfileResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_it_progetto_progetto_sdcc_proto_ProfileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_it_progetto_progetto_sdcc_proto_ProfileResponse_descriptor,
        new java.lang.String[] { "Profile", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
