// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/loginService.proto

package it.progetto.login.grpc;

public interface ProfileResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:it.progetto.progetto_sdcc.proto.ProfileResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string profile = 1;</code>
   * @return The profile.
   */
  java.lang.String getProfile();
  /**
   * <code>string profile = 1;</code>
   * @return The bytes for profile.
   */
  com.google.protobuf.ByteString
      getProfileBytes();
}
