// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/loginService.proto

package it.progetto.login.grpc;

public interface ProfileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:it.progetto.progetto_sdcc.proto.ProfileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string profile = 2;</code>
   * @return The profile.
   */
  java.lang.String getProfile();
  /**
   * <code>string profile = 2;</code>
   * @return The bytes for profile.
   */
  com.google.protobuf.ByteString
      getProfileBytes();
}
