version: "3.7"

services:

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"

  api_gateway:
    build: ./api_gateway
    ports:
      - "5000:5000"

  path_manager:
    build: ./pathManager
    depends_on:
     - db_path_manager
    ports:
      - "8081:8081"

  login:
    build: ./login
    depends_on:
      - db_login
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_login:5432/loginservice
    ports:
      - "9090:9090"


  review_manager:
    build: ./reviewManager
    depends_on:
      - db_review_manager
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_review_manager:5432/reviewmanager
    ports:
      - "9091:9091"

  weather_forecast:
    build: ./weatherForecast
    ports:
      - "9092:9092"

  visit_manager:
    build: ./visitManager
    depends_on:
      - db_visit_manager
    ports:
      - "9093:9093"

  db_path_manager:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: PathManager
      MYSQL_USER: pathmanager
      MYSQL_PASSWORD: password
    volumes:
      - ./data/pathManager:/docker-entrypoint-initdb.d
    ports:
      - "50000:3306"

  db_login:
    image: postgres
    container_name: db_login
    environment:
      DB: loginservice
      USER: login
      PASSWORD: password
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/login:/docker-entrypoint-initdb.d
    ports:
      - "50001:5432"

  db_review_manager:
    image: postgres
    container_name: db_review_manager
    environment:
      DB: reviewmanager
      USER: reviewmanager
      PASSWORD: password
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/reviewManager:/docker-entrypoint-initdb.d
    ports:
      - "50002:5432"

  db_visit_manager:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: VisitManager
      MYSQL_USER: visitmanager
      MYSQL_PASSWORD: password
    volumes:
      - ./data/visitManager:/docker-entrypoint-initdb.d
    ports:
      - "50003:3306"

volumes:
  db_login: {}
  db_path_manager: {}
  db_review_manager: {}
  db_visit_manager: {}