# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import notificationManager_pb2 as notificationManager__pb2


class NotificationManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInvites = channel.unary_unary(
                '/NotificationManager/GetInvites',
                request_serializer=notificationManager__pb2.InviteInput.SerializeToString,
                response_deserializer=notificationManager__pb2.InviteOutput.FromString,
                )


class NotificationManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetInvites(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInvites': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInvites,
                    request_deserializer=notificationManager__pb2.InviteInput.FromString,
                    response_serializer=notificationManager__pb2.InviteOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'NotificationManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NotificationManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInvites(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NotificationManager/GetInvites',
            notificationManager__pb2.InviteInput.SerializeToString,
            notificationManager__pb2.InviteOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
