# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notificationManager.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19notificationManager.proto\"\x1f\n\x0bInviteInput\x12\x10\n\x08Username\x18\x01 \x01(\t\"\x1f\n\x0cInviteOutput\x12\x0f\n\x07Invites\x18\x01 \x01(\t2@\n\x13NotificationManager\x12)\n\nGetInvites\x12\x0c.InviteInput\x1a\r.InviteOutputB\x13Z\x11\x61pi_gateway/protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notificationManager_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\021api_gateway/proto'
  _INVITEINPUT._serialized_start=29
  _INVITEINPUT._serialized_end=60
  _INVITEOUTPUT._serialized_start=62
  _INVITEOUTPUT._serialized_end=93
  _NOTIFICATIONMANAGER._serialized_start=95
  _NOTIFICATIONMANAGER._serialized_end=159
# @@protoc_insertion_point(module_scope)
