# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import weatherForecastService_pb2 as weatherForecastService__pb2


class WeatherForecastServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetForecast = channel.unary_unary(
                '/WeatherForecastService/GetForecast',
                request_serializer=weatherForecastService__pb2.ForecastInput.SerializeToString,
                response_deserializer=weatherForecastService__pb2.ForecastOutput.FromString,
                )


class WeatherForecastServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetForecast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WeatherForecastServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetForecast': grpc.unary_unary_rpc_method_handler(
                    servicer.GetForecast,
                    request_deserializer=weatherForecastService__pb2.ForecastInput.FromString,
                    response_serializer=weatherForecastService__pb2.ForecastOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'WeatherForecastService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WeatherForecastService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetForecast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/WeatherForecastService/GetForecast',
            weatherForecastService__pb2.ForecastInput.SerializeToString,
            weatherForecastService__pb2.ForecastOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
