# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weatherForecastService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cweatherForecastService.proto\"\x1d\n\rForecastInput\x12\x0c\n\x04Path\x18\x01 \x01(\t\"#\n\x0e\x46orecastOutput\x12\x11\n\tForecasts\x18\x01 \x01(\t2H\n\x16WeatherForecastService\x12.\n\x0bGetForecast\x12\x0e.ForecastInput\x1a\x0f.ForecastOutputB\x13Z\x11\x61pi_gateway/protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'weatherForecastService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\021api_gateway/proto'
  _FORECASTINPUT._serialized_start=32
  _FORECASTINPUT._serialized_end=61
  _FORECASTOUTPUT._serialized_start=63
  _FORECASTOUTPUT._serialized_end=98
  _WEATHERFORECASTSERVICE._serialized_start=100
  _WEATHERFORECASTSERVICE._serialized_end=172
# @@protoc_insertion_point(module_scope)
