// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/reviewManager.proto

package it.progetto.reviewmanager.grpc;

public interface AddReviewRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:it.progetto.progetto_sdcc.proto.AddReviewRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string review = 1;</code>
   * @return The review.
   */
  java.lang.String getReview();
  /**
   * <code>string review = 1;</code>
   * @return The bytes for review.
   */
  com.google.protobuf.ByteString
      getReviewBytes();
}
