// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/reviewManager.proto

package it.progetto.reviewmanager.grpc;

public interface AddReviewResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:it.progetto.progetto_sdcc.proto.AddReviewResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string addedReview = 1;</code>
   * @return The addedReview.
   */
  java.lang.String getAddedReview();
  /**
   * <code>string addedReview = 1;</code>
   * @return The bytes for addedReview.
   */
  com.google.protobuf.ByteString
      getAddedReviewBytes();
}
