// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/reviewManager.proto

package it.progetto.reviewmanager.grpc;

public interface GetReviewsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:it.progetto.progetto_sdcc.proto.GetReviewsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string mountainPathName = 1;</code>
   * @return The mountainPathName.
   */
  java.lang.String getMountainPathName();
  /**
   * <code>string mountainPathName = 1;</code>
   * @return The bytes for mountainPathName.
   */
  com.google.protobuf.ByteString
      getMountainPathNameBytes();
}
