// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/reviewManager.proto

package it.progetto.reviewmanager.grpc;

public interface GetReviewsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:it.progetto.progetto_sdcc.proto.GetReviewsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reviewsList = 1;</code>
   * @return The reviewsList.
   */
  java.lang.String getReviewsList();
  /**
   * <code>string reviewsList = 1;</code>
   * @return The bytes for reviewsList.
   */
  com.google.protobuf.ByteString
      getReviewsListBytes();
}
