// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/reviewManager.proto

package it.progetto.reviewmanager.grpc;

public final class ReviewManager {
  private ReviewManager() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_it_progetto_progetto_sdcc_proto_AddReviewRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_it_progetto_progetto_sdcc_proto_AddReviewRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_it_progetto_progetto_sdcc_proto_AddReviewResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_it_progetto_progetto_sdcc_proto_AddReviewResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_it_progetto_progetto_sdcc_proto_GetReviewsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_it_progetto_progetto_sdcc_proto_GetReviewsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_it_progetto_progetto_sdcc_proto_GetReviewsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_it_progetto_progetto_sdcc_proto_GetReviewsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&src/main/resources/reviewManager.proto" +
      "\022\037it.progetto.progetto_sdcc.proto\"\"\n\020Add" +
      "ReviewRequest\022\016\n\006review\030\001 \001(\t\"(\n\021AddRevi" +
      "ewResponse\022\023\n\013addedReview\030\001 \001(\t\"-\n\021GetRe" +
      "viewsRequest\022\030\n\020mountainPathName\030\001 \001(\t\")" +
      "\n\022GetReviewsResponse\022\023\n\013reviewsList\030\001 \001(" +
      "\t2\201\002\n\024ReviewManagerService\022r\n\taddReview\022" +
      "1.it.progetto.progetto_sdcc.proto.AddRev" +
      "iewRequest\0322.it.progetto.progetto_sdcc.p" +
      "roto.AddReviewResponse\022u\n\ngetReviews\0222.i" +
      "t.progetto.progetto_sdcc.proto.GetReview" +
      "sRequest\0323.it.progetto.progetto_sdcc.pro" +
      "to.GetReviewsResponseB\"\n\036it.progetto.rev" +
      "iewmanager.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_it_progetto_progetto_sdcc_proto_AddReviewRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_it_progetto_progetto_sdcc_proto_AddReviewRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_it_progetto_progetto_sdcc_proto_AddReviewRequest_descriptor,
        new java.lang.String[] { "Review", });
    internal_static_it_progetto_progetto_sdcc_proto_AddReviewResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_it_progetto_progetto_sdcc_proto_AddReviewResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_it_progetto_progetto_sdcc_proto_AddReviewResponse_descriptor,
        new java.lang.String[] { "AddedReview", });
    internal_static_it_progetto_progetto_sdcc_proto_GetReviewsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_it_progetto_progetto_sdcc_proto_GetReviewsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_it_progetto_progetto_sdcc_proto_GetReviewsRequest_descriptor,
        new java.lang.String[] { "MountainPathName", });
    internal_static_it_progetto_progetto_sdcc_proto_GetReviewsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_it_progetto_progetto_sdcc_proto_GetReviewsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_it_progetto_progetto_sdcc_proto_GetReviewsResponse_descriptor,
        new java.lang.String[] { "ReviewsList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
